[package]
name = "llm-pentester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version="*", features = ["blocking", "json", "rustls-tls"], default-features=false}
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
axum = { version="*", features=["json", "tokio"] }
tokio = { version="*", features = ["rt", "macros", "fs", "process", "sync"] }
tower-http = { version = "*", features = ["cors", "fs"] }
http = "*"
tokio-stream = "*"
tempdir = "*"
rand = "*"
anyhow = "*"
html-escape = "*"
futures = "*"